kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha5
name: diploma
nodes:
  - role: control-plane
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            system-reserved: memory=6Gi,cpu=2
  #- role: worker
